apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-zip
spec:
  selector:
    matchLabels:
      app: zipapp
  replicas: 1
  template:
    metadata:
      labels:
        app: zipapp
    spec:
      containers:
        - name: zip
          image: mjlee39/woorizip:0.1.1
          ports:
            - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: service-zip
spec:
  selector:
    app: zipapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
  type: NodePort

