apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-zip
spec:
  selector:
    matchLabels:
      app: zip
  replicas: 1
  template:
    metadata:
      labels:
        app: zip
    spec:
      containers:
        - name: zipapp
          image: 211125685751.dkr.ecr.ap-northeast-2.amazonaws.com/woorizip-zip:20240508093017
          ports:
            - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: service-zip
spec:
  selector:
    app: zip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
  type: NodePort