server:
  port: 0   # server.port=80
#  servlet:
#    context-path: /zip  # server.servlet.context-path=/probono
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://woorizip-database.c56y0ki2ky4c.ap-northeast-2.rds.amazonaws.com:3306/teamwafdb?serverTimezone=Asia/Seoul
    #url: jdbc:mysql://mysqlcommdb:3306/fisa?useSSL=false&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://127.0.0.1:3306/fisa?useSSL=false&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://db17.cfaa2gyks0rb.ap-northeast-2.rds.amazonaws.com:3306/fisa?useSSL=false&allowPublicKeyRetrieval=true
    username: teamwaf
    password: dntmdrhkaudtjd12
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

grpc:
  server:
    port: 9091
    address: 0.0.0.0
  client:
    estate-server: # 이건 gRPC 서버 이름 지정 아무거나 가능
      address: 'static://service-zip.woorizip.svc.cluster.local:80' # static 뒤에 gRPC 서버의 주소와 포트
      negotiation-type: plaintext # 통신 할 때 방식

